### PR TITLE
Ci fixes

### PR DESCRIPTION
**Pull request by antonblanchard**
This gets the CI closer to working again. One remaining problem is in the miniconda installer https://github.com/conda/conda/issues/10431

### CODE REVIEW

**Comment by mithro** [comment]
I assume the issue is the SkyWater PDK? If we update the `third_party/make-env` submodule to the latest version that should work again -> https://github.com/SymbiFlow/make-env/pull/31

**Comment by mithro** [comment]
https://github.com/google/skywater-pdk/pull/408 should fix the problem?

**Comment by antonblanchard** [comment]
Thanks @mithro it does, and the CI is now passing with the skywater make-env fix and this PR. Thanks!

**Review by RTimothyEdwards — APPROVED** [review]
I don't really understand how this affects the CI operation, but I'll take your word for it.

**Comment by RTimothyEdwards** [comment]
Pulled and merged (but not yet mirrored to github).

**Pull request closed without merging**
