### PR TITLE
openlane config updates (PR #30 and #31):

### PR DESCRIPTION
**Pull request by agorararmard**
-    no_synth.cells cleanup
-    first go at no_synth.cells reduction
-    variables cleanup
-    core_ring support
-    Initial attempt at creating a more generic common_pdn.tcl (covering macros and cores)

### CODE REVIEW

**Comment by agorararmard** [comment]
@RTimothyEdwards: This, hopefully, shouldn't cause any conflicts.

**Comment by agorararmard** [comment]
Hi @RTimothyEdwards, is there something blocking the merging of this pull request (something I should change)?

**Comment by RTimothyEdwards** [comment]
@agorararmard :  Sorry, the blockage is the amount of time that I have to review it and do something about it.  Looking at it now.

**Review by RTimothyEdwards — APPROVED** [review]
All looks good to me.

**Comment by RTimothyEdwards** [comment]
Pull request has been merged.

**Pull request closed without merging**
