### PR TITLE
Adding Klayout device generators as sub module for Open PDKs

### PR DESCRIPTION
**Pull request by atorkmabrains**
Adding Klayout Device Generators to Open PDKs.

### CODE REVIEW

**Review by RTimothyEdwards — COMMENTED** [review]
I don't use submodules in open_pdks.  I can pull it in as a third-party repository by cloning into sources/.

**Review by RTimothyEdwards — COMMENTED** [review]
How do you differentiate between sky130A and sky130B?

**Review by RTimothyEdwards — COMMENTED** [review]
I just implemented this in open_pdks with a clone on your repository from the Makefile.

**Comment by RTimothyEdwards** [comment]
@atorkmabrains :  If you can confirm the implementation in open_pdks through cloning, I will close this pull request.

**Comment by atorkmabrains** [comment]
Hey @RTimothyEdwards 
I don't have a problem with that but how would you get all the new updates?

Would you do that manually?

-Amro

**Comment by atorkmabrains** [comment]
That sounds great

**Comment by RTimothyEdwards** [comment]
I believe everything is working smoothly with the cloned repository, so I'm going to go ahead and close this ticket.

**Pull request closed without merging**
