### PR TITLE
project_manager uses info.yaml for basic project information

### PR DESCRIPTION
**Pull request by emayecs**
Replaced project.json with info.yaml in places asking for basic project info. Renamed some variables that still referred to 'og.' Added create_yaml() method. The create_project script creates the yaml file using the yaml loader instead of printing directly into the yaml file.

### CODE REVIEW

**Review by RTimothyEdwards — CHANGES_REQUESTED** [review]
Two things:

(1) Why did foundry_nodes.py line 1 change from "/usr/bin/env python3" (correct) to "/usr/bin/python" (incorrect)?

(2) There are a couple of references to Open Galaxy in comments and such using the phrase "Open Galaxy" that should be removed (I see one in profile.py;  there might be others).

**Comment by emayecs** [comment]
Sorry about that Mr. Edwards; I think I copied the original copy of foundry_nodes.py with the old line on accident.

**Review by RTimothyEdwards — APPROVED** [review]
Looks good to me.

**Comment by RTimothyEdwards** [comment]
Pulled and merged.

**Pull request closed without merging**
