### PR TITLE
Initial attempt at creating a more generic common_pdn.tcl (covering macros and cores)

### PR DESCRIPTION
**Pull request by agorararmard**

### CODE REVIEW

**Comment by RTimothyEdwards** [comment]
Somehow I missed this merge request.  I can do that now.

**Comment by RTimothyEdwards** [comment]
I am unable to merge this.

**Comment by agorararmard** [comment]
I'm guessing that's because #30 didn't get pushed to the repo somehow. Can you merge #30, so I'd be able to renew this PR without the tailing commits?

**Comment by agorararmard** [comment]
@RTimothyEdwards I'll rebase with master and resubmit #30 and #31 in one PR.

**Pull request closed without merging**
