### PR TITLE
Fix unterminated #ifdef in magic/sky130.tech

### PR DESCRIPTION
**Pull request by antonblanchard**

### CODE REVIEW

**Comment by antonblanchard** [comment]
@RTimothyEdwards I'm guessing this is where it should go, but please double check I got it right.

**Review by RTimothyEdwards — APPROVED** [review]
Apparently my preprocessor script misses underminated ifdefs?

**Comment by RTimothyEdwards** [comment]
Pulled and merged.

**Comment by antonblanchard** [comment]
> Apparently my preprocessor script misses underminated ifdefs?

It does complain, but I guess it doesn't cause the build to error out. I noticed it because I was redirecting stdout to a file and I got a couple of warnings to stderr.

**Comment by antonblanchard** [comment]
Closing

**Pull request closed without merging**
