### PR TITLE
old names changed to new ones in tcl and tech file

### PR DESCRIPTION
**Pull request by qurratulainalam**

### CODE REVIEW

**Review by RTimothyEdwards — CHANGES_REQUESTED** [review]
If you could please do one more commit with two additional things:
(1) Change "subconfet" in line 391 to "subcon"
(2) Remove all of the routines with `np_6p0` which no longer corresponds to any device
(np_6p0_defaults, np_6p0_convert, np_6p0_dialog, np_6p0_draw, np_6p0_check).

**Comment by qurratulainalam** [comment]
Sure i can do thst just give me 30 mins and I'll update you about that i am
on my way home right now

**Review by RTimothyEdwards — CHANGES_REQUESTED** [review]
You were only supposed to remove the procedures involving `np_6p0_nat` but you deleted a number of other routines as well, which will break the device generator.

**Comment by RTimothyEdwards** [comment]
Oh, I'm sorry, I gave the wrong instructions to you.  Can you revert that last commit?  The instructions should have been to remove all routines with `np_6p0_nat`.

**Comment by RTimothyEdwards** [comment]
I'm going to go ahead and merge this and then commit back the missing routines.  The original issue with incorrect names keeps any changes from being tested properly.  I should have merged the previous commit.

**Review by RTimothyEdwards — APPROVED** [review]
Will take this version and put back the routines that got deleted due to my bad instructions.

**Comment by RTimothyEdwards** [comment]
Pulled and merged.  Will close this PR and mirror the merged repo to github after testing.

**Comment by RTimothyEdwards** [comment]
Testing looks good.  I will close this PR and mirror the repo back to github.

**Pull request closed without merging**
