### PR TITLE
Allow the addition of a user-specific path for XSCHEM

### PR DESCRIPTION
**Pull request by hpretl**
This is a useful feature for containerized installations, see https://github.com/iic-jku/iic-osic-tools/issues/7.

### CODE REVIEW

**Comment by curtisma** [comment]
It is used as the base image in the following [devcontainer](https://containers.dev/) template:
https://github.com/cascode-labs/viper-ic-devcontainers

It makes it easy to use [Visual Studio (VS) code's devcontainer support](https://code.visualstudio.com/docs/devcontainers/containers) and its user interface for open-source integrated circuit development.

**Review by RTimothyEdwards — APPROVED** [review]
Looks good to me.

**Comment by RTimothyEdwards** [comment]
Pulled and merged (on opencircuitdesign.com).  I can force a mirror to github during the day if you need it.

**Comment by hpretl** [comment]
Thanks a lot! No fast forwarding, needed, we can let it trickle through the system :-)

**Comment by curtisma** [comment]
Thanks @RTimothyEdwards and @hpretl!

**Comment by curtisma** [comment]
Should we close this?

**Comment by hpretl** [comment]
Integrated, se we can close.

**Pull request closed without merging**
