### PR TITLE
sky130: skip xschem files copy when disabled

### LINKED ISSUE #214: --disable-xschem-sky130 still tries to access xschem/sky130_tests
Possibly related to #177 it seems that `--disable-xschem-sky130` doesn't disable all of the xschem related rules:
```
#add the correct libraries into the test files
for file in $SRC_DIR/sky130/sky130A/libs.tech/xschem/sky130_tests/* ; do \
	/usr/bin/sed -i '/.include $\:\:SKYWATER_MODELS/d' $file ; \
	grep -zl 'sky130.lib.spice' $file || /usr/bin/sed -z 's|format="tcleval( @value )"\nvalue="|format="tcleval( @value )"\nvalue="\n.lib $\:\:SKYWATER_MODELS/sky130.lib.spice tt |' -i $file ; \
done
/usr/bin/sed: can't read /home/proppy/src/github.com/hdl/conda-eda/env/conda-bld/open_pdks_1643764606273/work/sky130/sky130A/libs.tech/xschem/sky130_tests/*: No such file or directory
grep: /home/proppy/src/github.com/hdl/conda-eda/env/conda-bld/open_pdks_1643764606273/work/sky130/sky130A/libs.tech/xschem/sky130_tests/*: No such file or directory
/usr/bin/sed: can't read /home/proppy/src/github.com/hdl/conda-eda/env/conda-bld/open_pdks_1643764606273/work/sky130/sky130A/libs.tech/xschem/sky130_tests/*: No such file or directory
make[2]: *** [Makefile:826: xschem-A] Error 2
```

### PR DESCRIPTION
**Pull request by proppy**
Fixes #214 

Note this add multiple `if` blocks in order to keep the existing `# comments` structure, let me know if you'd prefer to have a single one.

### CODE REVIEW

**Review by RTimothyEdwards — APPROVED** [review]
I agree that this is related to #177 and probably the same approach needs to be taken for each section of the Makefile that can be changed with a "disable" option.

I would have put everything there in a single "if" block, but anyway, it looks like it works.

**Comment by proppy** [comment]
> I would have put everything there in a single "if" block, but anyway, it looks like it works.

me too, but then it messes with the `# comments` as everything needs to get folded into oneline, any `Makefile`-fu to workaround this?

**Comment by RTimothyEdwards** [comment]
No, I'm okay with your syntax.  Any chance you could fix the problems with the other disable options?  : )

**Comment by proppy** [comment]
@RTimothyEdwards sure! in a different PR?

**Comment by RTimothyEdwards** [comment]
Yes, please.  I already merged this one (into my repo at opencircuitdesign.com).

**Pull request merged**
