### PR TITLE
Update no_synth.cells

### PR DESCRIPTION
**Pull request by ax3ghazy**

### CODE REVIEW

**Comment by RTimothyEdwards** [comment]
Pulled and merged

**Comment by riking** [comment]
I've seen several of these giant updates to no_synth.cells with zero explanation - are they automatically generated somehow?

**Comment by ax3ghazy** [comment]
@riking: Yes, I should've left some notes. This is the list of cells, on which I was able to cleanly build mgmt_core in caravel. I have allowed two smaller inverters, and removed some other smaller cells that were causing pin access/congestion issues. The changes aren't that drastic though in this patch. What are your concerns?

They are not automatically generated, but when we face pin access issues in a certain (complex/important) design, we may revise them based on the issues we see.

**Comment by mithro** [comment]
@ax3ghazy -- This very much feels like you are solving the problem in the wrong way here...

**Comment by riking** [comment]
> pin access/congestion issues

This doesn't feel like a valid justification for a global cell banlist - at most, cells causing generic routing congestion should go on a per-project ban list.

**Comment by ax3ghazy** [comment]
I agree; however, most of the time it's more than generic routing congestion. Sometimes the cell is just badly designed, having very tightly-placed or small pins surrounded by obstructions or things like that.

Anyway, the root causes of each of those excludes should be addressed or at least be well-documented. I started a spreadsheet for that purpose at https://docs.google.com/spreadsheets/d/1yujIXMO6jPaVmauqBKc8yL1-ldw_oBhtySXgKSNQ4nM/edit#gid=0 (will also put on several READMEs).

**Pull request closed without merging**
