### PR TITLE
fixed bugs with sealring_generator

### PR DESCRIPTION
**Pull request by emayecs**
Fixed bug so that the temp directory is created in the working directory instead of the directory where the script is located. The script also checks if the working directory is writable. Finally, the script also checks if "tmp" is an available directory if "temp" is already taken.

### CODE REVIEW

**Review by RTimothyEdwards — CHANGES_REQUESTED** [review]
The only issue is that the fallback directory should be in '/tmp'.  Since that's a global directory used by everyone, the name should be specific to the sealring generator, so maybe something like '/tmp/sky130_sealring".  It is supposed to be a fallback that always succeeds, so the procedure should be (1) check directory "temp" in current working directory;  (2) if that already exists or cannot be created, then print a message saying so, then (3) check directory "/tmp/sky130_sealring".  If that exists, then remove all of its contents.  If it doesn't exist, then create it.  If it cannot be created, then exit with error code 1 (my mistake in giving it a success code of zero) (/tmp by definition is supposed to be writeable, so this shouldn't fail, but you never know).

**Review by RTimothyEdwards — APPROVED** [review]
Looks good;  I'll go ahead and merge this.

**Comment by RTimothyEdwards** [comment]
@emayecs :  The way this works is that I do a merge into the repository at opencircuitdesign.com.  The github repository is a mirror of opencircuitdesign.com and updates at 3:00 in the morning.  If you have cloned from github and need an immediate update for any reason, I can force the mirror copy.

Otherwise, this pull request has been pulled and merged.

**Comment by emayecs** [comment]
Sounds good, thanks!

**Pull request closed without merging**
