### PR TITLE
Added separate lyp/lyt files for the B flow and renamed the others to…

### PR DESCRIPTION
**Pull request by mkkassem**
… include A (TE to double check the impact on open_pdks build)

The sky130B.lyt/p files include the ReRAM layers

r1c		drawing		201	20
r1c		pin		    201	251
r1c		label		201	237
r1c		res		    201	16
r1c		net		    201	253
r1c		mask		201	0
r1c		fill_block	201	24
r1c		blockage	201	230
r1c		boundary	201	4
r1v		drawing		202	20
r1v		pin		202	251
r1v		label		202	237
r1v		res		202	16
r1v		net		202	253
r1v		mask		202	0
r1v		fill_block	202	24
r1v		blockage	202	230
r1v		boundary	202	4

### CODE REVIEW

**Comment by RTimothyEdwards** [comment]
@mkkassem :  Do not post a pull request that breaks the installation.  Just send me the new files.

**Comment by RTimothyEdwards** [comment]
Anyway, I no longer keep klayout files for sky130 in open_pdks.  They come from https://github.com/mabrains/sky130_klayout_pdk.  So changes need to be made there.

**Comment by mkkassem** [comment]
> Anyway, I no longer keep klayout files for sky130 in open_pdks. They come from https://github.com/mabrains/sky130_klayout_pdk. So changes need to be made there.

This above repo is not a tested/nor does it contain complete representation/nor is it regularly maintained for SKY130 KLayout sources. We are in the process of shifting and reactivating the maintenance of the content to have coverage for SKY130 and planning to push it upstream in the main google skywater-pdk if we believe that the pull requests to google will be tested/included otherwise we will have to maintain it in a fork or a separate repo.

**Comment by mkkassem** [comment]
These updates to the KLayout .lyp/.lyt files will be redirected to another update process. Meanwhile it Klayout users can add the files manually to the $PDK_ROOT/sky130B/libs.tech/klayout as a patch **after** the open_pdk build is completed.

The files will be located here until a better location is identified. https://github.com/mkkassem/open_pdks/tree/master/sky130/klayout

**Pull request closed without merging**
