### PR TITLE
Reapply connect/disconnect cell fixes from fe967d6

### PR DESCRIPTION
**Pull request by ax3ghazy**
This is a follow-up on #81.

It's a bit confusing to submit PRs when the changes are getting merged into another repo. Commits that exist in the opencircuitdesign repo but not here will be shown below every time... Is it easy/feasible to force mirror when PRs get merged?

### CODE REVIEW

**Comment by RTimothyEdwards** [comment]
@ax3ghazy :  Yes.  Just tell me to force a mirror right away, and I can do it.  What way is best to do right now, as I have not yet merged this pull request?

**Comment by ax3ghazy** [comment]
@RTimothyEdwards: For now you could just merge them at opencircuitdesign and wait for the overnight mirror as usual since I am not planning further PRs for today. I will let you know in the future if forcing a mirror is preferred. Thanks!

**Comment by RTimothyEdwards** [comment]
Okay;  I'll try to make sure to get around to merging this in a little bit.

**Comment by RTimothyEdwards** [comment]
Pulled, merged, and mirrored.

**Pull request closed without merging**
